language: node_js

node_js:
  - 10

cache:
  yarn: true
  directories:
    - node_modules

env:
  - NODE_ENV=test

script:
    - yarn validate

after_script:
    - cat ./coverage/lcov.info | coveralls